from selenium.webdriver.common.by import By


class ProductInfoPageLocators:
    addToCart_button = (By.XPATH, "//button[@id='button-cart']")
    black_item_button = (By.XPATH, "//button[@class='btn btn-inverse btn-block btn-lg dropdown-toggle']")
    success_message = (By.XPATH, "//div[@class='alert alert-success alert-dismissible']")
    shopping_cart_link = (By.XPATH, "//div[@class='alert alert-success alert-dismissible']//a[text()='shopping cart']")
    quantity_input_field = (By.XPATH, "//input[@id='input-quantity']")
    # add_to_cart_product_page = (By.XPATH, "//button[@id='button-cart']")
    product_name = (By.XPATH, "//div[@class='col-sm-4']//h1")
    # product_list_elements =(By.XPATH, "//div[@class='col-sm-4']//ul[1]//li")
    product_brand = (By.XPATH, "//div[@class='col-sm-4']//ul//li//a")
    product_code = (By.XPATH, "//ul//li[text()='Product Code: Product 14']")  # "//ul//li[contains(text(), 'Product Code:')]"
    black_item_button_text = (By.ID, "cart-total")
    minimum_quantity_text_box = (By.XPATH, "//div[@class='alert alert-info']")
    medium_radio = (By.NAME, "option[218]")
    checkbox_three = (By.NAME, "option[223][]")
    text_input_field = (By.ID, "input-option208")
    dropdown_button = (By.ID, "input-option217")
    text_input_area = (By.XPATH, "//textarea[@id='input-option209']")
    upload_file_button = (By.ID, "input-option222")
    button_upload_file = (By.ID, "button-upload222")
    calendar_date_picker_icon = (By.XPATH, "//div[@class='input-group date']//button[@type='button']")
    month_year_date_button = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='datepicker-days']//table//thead//tr[1]//th[2]")
    right_arrow_button = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='datepicker-days']//table//thead//tr[1]//th[3]")
    left_arrow_button = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='datepicker-days']//table//thead//tr[1]//th[1]")
    calendar_days = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='datepicker-days']//table//tbody//tr//td[@class='day']")
    calendar_time_picker_icon = (By.XPATH, "//div[@class='input-group time']//button[@type='button']")
    calendar_hour_box = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='timepicker-picker']//table//tbody//tr[2]//td[1]//span")
    calendar_minutes_box = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='timepicker-picker']//table//tbody//tr[2]//td[3]//span")
    calendar_hour_arrow_button_up = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='timepicker-picker']//table//tbody//tr[1]//td[1]//span")
    calendar_minutes_arrow_button_up = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='timepicker-picker']//table//tbody//tr[1]//td[3]//span")
    calendar_hour_arrow_button_down = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='timepicker-picker']//table//tbody//tr[3]//td[1]//span")
    calendar_minutes_arrow_button_down = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'picker-open')]//div[@class='timepicker-picker']//table//tbody//tr[3]//td[3]//span")
    calendar_date_time_icon = (By.XPATH, "//div[@class='input-group datetime']//button[@type='button']")
    date_time_month_year_button = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//div[@class='datepicker-days']//table//thead//tr[1]//th[2]")
    date_time_right_arrow_button = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//div[@class='datepicker-days']//table//thead//tr[1]//th[3]")
    date_time_left_arrow_button = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//div[@class='datepicker-days']//table//thead//tr[1]//th[1]")
    date_time_calendar_days = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//div[@class='datepicker-days']//table//tbody//tr//td[@class='day']")
    date_time_hour_button = (By.XPATH, "//li[@class='picker-switch accordion-toggle']")
    date_time_hour_box = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//table//tbody//tr[2]//td[1]//span")
    date_time_minutes_box = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//table//tbody//tr[2]//td[3]//span")
    date_time_hour_arrow_button_up = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//table//tbody//tr[1]//td[1]//a")
    date_time_minutes_arrow_button_up = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//table//tbody//tr[1]//td[3]//a")
    date_time_hour_arrow_button_down = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//table//tbody//tr[3]//td[1]//a")
    date_time_minutes_arrow_button_down = (By.XPATH, "//div[contains(@class,'bootstrap-datetimepicker-widget') and contains(@class,'usetwentyfour')]//table//tbody//tr[3]//td[3]//a")
    # //div[contains(@class,"usetwentyfour")]
    reviews_button = (By.XPATH, "//div[@class='col-sm-8']//ul[@class='nav nav-tabs']//li//a[text()='Reviews (0)']")
    name_input_reviews = (By.XPATH, "//input[@id='input-name']")
    reviews_message = (By.XPATH, "//textarea[@id='input-review']")
    radio_buttons_reviews = (By.XPATH, "//div[@class='form-group required']//input[@type='radio']")
    continue_button_reviews = (By.XPATH, "//button[@id='button-review']")
    success_message_reviews = (By.XPATH, "//div[@class='alert alert-success alert-dismissible' and contains(text(), 'Thank you for your review.')]")
    warning_review_text_message = (By.XPATH, "//div[contains(@class, 'alert-danger') and contains(text(), 'Warning') and contains(text(), 'Review Text')]")
    warning_review_name_message = (By.XPATH, "//div[contains(@class, 'alert-danger') and contains(text(), 'Warning') and contains(text(), 'Review Name')]")
    warning_review_rating_message = (By.XPATH, "//div[contains(@class, 'alert-danger') and contains(text(), 'Warning') and contains(text(), 'review rating')]")